[package]
name = "ex-rtic"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
embedded-hal = { version = "1.0.0" }
fugit = "0.3.7"
panic-probe = "0.3.2"
portable-atomic = {version = "1.10.0", features = ["critical-section"]}
rp-pico = "0.9.0"
rtic = {version = "2.1.2", features = ["thumbv6-backend"]}
rtic-monotonics = {version = "2.0.3", features = ["rp2040"]}
