[package]
name = "minimal-alloc"
version = "0.1.0"
edition = "2021"

[dependencies]
fixed = { version = "1.28.0", features = ["serde"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
